-- AlterEnum: rename role values
ALTER TYPE "UserRole" RENAME VALUE 'TENANT_ADMIN' TO 'UNIVERSITY';
ALTER TYPE "UserRole" RENAME VALUE 'ISSUER' TO 'OPERATOR';
ALTER TYPE "UserRole" RENAME VALUE 'AUDITOR' TO 'VERIFIER';
